server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    metadataMap.zone: zone1
  client:
    registerWithEureka: true
    fetchRegistry: true
    region: region-east
    serviceUrl:
      #      defaultZone: http://localhost:8761/eureka/ # one eureka server
#      defaultZone: http://localhost:8762/eureka/ # two eureka server
#      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/ # three eureka server
#      多zone区演示
#      zone1: http://localhost:8761/eureka/,http://localhost:8762/eureka/
#      zone2: http://localhost:8763/eureka/,http://localhost:8764/eureka/
      zone1: http://localhost:8761/eureka/
      zone2: http://localhost:8762/eureka/
    availability-zones:
#      region-east: zone1,zone2
      region-east: zone1,zone2
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false
    remoteRegionUrlsWithName:
      region-west: http://localhost:8763/eureka/