server:
  port: 8764

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    metadataMap.zone: zone4
  client:
    registerWithEureka: true
    fetchRegistry: true
    region: region-west
    serviceUrl:
      #      defaultZone: http://localhost:8761/eureka/ # one eureka server
#      defaultZone: http://localhost:8762/eureka/ # two eureka server
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/ # three eureka server
#      zone1: http://localhost:8761/eureka/,http://localhost:8762/eureka/
#      zone2: http://localhost:8763/eureka/,http://localhost:8764/eureka/
      zone3: http://localhost:8763/eureka/
      zone4: http://localhost:8764/eureka/
    availability-zones:
#      region-east: zone1,zone2
      region-west: zone3,zone4
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false
    remoteRegionUrlsWithName:
      region-east: http://localhost:8761/eureka/