server:
  port: 8081

spring:
  application:
    name: eureka-client1

eureka:
  instance:
    metadataMap.zone: zone1
  client:
    region: region-east
    service-url:
#      one eureka server
#      defaultZone: http://localhost:8761/eureka/
#      two eureka server
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
      zone1: http://localhost:8761/eureka/,http://localhost:8762/eureka/
      zone2: http://localhost:8763/eureka/,http://localhost:8764/eureka/
    availability-zones:
      region-east: zone1,zone2