server:
  port: 5555

spring:
  application:
    name: zuul-server
  datasource:
    url: jdbc:mysql://120.78.210.146:3306/sampledb?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Zh@123456
  #文件上传
  servlet: #spring-boot 2.0之前是http
    multipart:
      enabled: true #使用http multipart上传处理
      max-file-size: 100MB #单个文件最大长度，-1为不限制
      max-request-size: 100MB #设置最大的请求文件的大小，默认10MB，-1为不限制
      file-size-threshold: 1MB #当上传文件达到1MB的时候进行磁盘写入
      location: / #上传的临时目录
  cloud:
    loadbalancer:
      retry:
        enabled: true #内部默认已开启，这里列出来说明这个参数比较重要


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

zuul:
  retryable: true #开启重试，D版之后默认为false，需要手动开启
  ribbon:
    eager-load:
      enabled: true #开启饥饿加载模式
#  routes:
#    client-a: /client/**
  ratelimit:
    key-prefix: springcloud #按粒度拆分的临时变量key前缀
    enabled: true #启用开关
    repository: IN_MEMORY #key存储类型，默认是IN_MEMORY本地内存，此外还有多种形式
    behind-proxy: true #表示代理之后
    default-policy: #全局限流策略，可单独细化到服务力度
      limit: 2 #在一个单位时间窗口的请求量
      quota: 1 #在一个单位时间窗口的请求时间限制
      refresh-interval: 3 #单位时间窗口
#      type:
#        - user #可指定用户粒度
#        - origin #可指定客户端地址粒度
#        - url #可指定url粒度

#禁用HttpClient并开启OkHttp
ribbon:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
#重试机制配置
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
  MaxAutoRetries: 1 #对第一次请求的服务的重试次数
  MaxAutoRetriesNextServer: 1 #要重试的下一个服务的最大数量（不包括第一个服务）
  OkToRetryOnAllOperations: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

#security:
#  basic:
#    enabled: false
#  oauth2:
#    client:
#      access-token-uri: http://localhost:7777/uaa/oauth/token #令牌端点
#      user-authorization-uri: http://localhost:7777/uaa/oauth/authorize #授权端点
#      client-id: zuul_server #oauth2客户端id
#      client-secret: secret #oauth2客户端秘钥
#    resource:
#      jwt:
#        key-value: springcloud123 #使用对称加密方式，默认算法为HS256
