server:
  port: 9090
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zhudemiung/spring-cloud-org.lql.config.git
          search-paths: SC-BOOK-CONFIG
  application:
    name: sc-configserver
