server:
  port: 8020

spring:
  application:
    name: consumer-service

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'