server:
  port: 7070

spring:
  application:
    name: client-a

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      host-mark: running-host #灰度发布使用
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
